// <auto-generated>
/*
 * Dona API
 *
 * Dona API v1 (https://api.dona.im/seller-api/v1) — client generated from the OpenAPI contract. Conventions (auth, errors, idempotency, dry_run, rate limits, 202 held_for_review): https://github.com/ozbuz/dona-api#readme · contract: https://api.dona.im/seller-api/v1/openapi.json
 *
 * The version of the OpenAPI document: v1 (frozen 2026-09-24)
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net;
using System.IO;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using Dona.Api.Client;
using Dona.Api.Logging;
using Dona.Api.Model;
using System.Diagnostics.CodeAnalysis;

namespace Dona.Api.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface IKeysApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        KeysApiEvents Events { get; }

        /// <summary>
        /// The shop&#39;s keys (read-only; management is portal-only)
        /// </summary>
        /// <remarks>
        /// Metadata only — never a secret, never &#x60;last_used_ip&#x60;. Mint/rotate/revoke live in the seller portal.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="acceptLanguage">Localises &#x60;message&#x60; in error bodies and single-language renderings. Default &#x60;uz&#x60;. (optional, default to &quot;uz&quot;)</param>
        /// <param name="xDonaIntegration">&#x60;name/version&#x60; of the calling integration; stored (≤ 128 chars) and searchable in the request journal. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListKeysApiResponse"/>&gt;</returns>
        Task<IListKeysApiResponse> ListKeysAsync(Option<string> acceptLanguage = default, Option<string> xDonaIntegration = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// The shop&#39;s keys (read-only; management is portal-only)
        /// </summary>
        /// <remarks>
        /// Metadata only — never a secret, never &#x60;last_used_ip&#x60;. Mint/rotate/revoke live in the seller portal.
        /// </remarks>
        /// <param name="acceptLanguage">Localises &#x60;message&#x60; in error bodies and single-language renderings. Default &#x60;uz&#x60;. (optional, default to &quot;uz&quot;)</param>
        /// <param name="xDonaIntegration">&#x60;name/version&#x60; of the calling integration; stored (≤ 128 chars) and searchable in the request journal. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListKeysApiResponse"/>?&gt;</returns>
        Task<IListKeysApiResponse?> ListKeysOrDefaultAsync(Option<string> acceptLanguage = default, Option<string> xDonaIntegration = default, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="IListKeysApiResponse"/>
    /// </summary>
    public interface IListKeysApiResponse : Dona.Api.Client.IApiResponse, IOk<Dona.Api.Model.KeyPage?>, IUnauthorized<Dona.Api.Model.Error?>, IForbidden<Dona.Api.Model.Error?>, ITooManyRequests<Dona.Api.Model.Error?>, IInternalServerError<Dona.Api.Model.Error?>, IServiceUnavailable<Dona.Api.Model.Error?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 401 Unauthorized
        /// </summary>
        /// <returns></returns>
        bool IsUnauthorized { get; }

        /// <summary>
        /// Returns true if the response is 403 Forbidden
        /// </summary>
        /// <returns></returns>
        bool IsForbidden { get; }

        /// <summary>
        /// Returns true if the response is 429 TooManyRequests
        /// </summary>
        /// <returns></returns>
        bool IsTooManyRequests { get; }

        /// <summary>
        /// Returns true if the response is 500 InternalServerError
        /// </summary>
        /// <returns></returns>
        bool IsInternalServerError { get; }

        /// <summary>
        /// Returns true if the response is 503 ServiceUnavailable
        /// </summary>
        /// <returns></returns>
        bool IsServiceUnavailable { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class KeysApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnListKeys;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorListKeys;

        internal void ExecuteOnListKeys(KeysApi.ListKeysApiResponse apiResponse)
        {
            OnListKeys?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorListKeys(Exception exception)
        {
            OnErrorListKeys?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class KeysApi : IKeysApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<KeysApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public KeysApiEvents Events { get; }

        /// <summary>
        /// A token provider of type <see cref="BearerToken"/>
        /// </summary>
        public TokenProvider<BearerToken> BearerTokenProvider { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="KeysApi"/> class.
        /// </summary>
        /// <returns></returns>
        public KeysApi(ILogger<KeysApi> logger, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, KeysApiEvents keysApiEvents,
            TokenProvider<BearerToken> bearerTokenProvider)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            Logger = logger;
            HttpClient = httpClient;
            Events = keysApiEvents;
            BearerTokenProvider = bearerTokenProvider;
        }

        partial void FormatListKeys(ref Option<string> acceptLanguage, ref Option<string> xDonaIntegration);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="acceptLanguage"></param>
        /// <param name="xDonaIntegration"></param>
        /// <returns></returns>
        private void ValidateListKeys(Option<string> acceptLanguage, Option<string> xDonaIntegration)
        {
            if (acceptLanguage.IsSet && acceptLanguage.Value == null)
                throw new ArgumentNullException(nameof(acceptLanguage));

            if (xDonaIntegration.IsSet && xDonaIntegration.Value == null)
                throw new ArgumentNullException(nameof(xDonaIntegration));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="acceptLanguage"></param>
        /// <param name="xDonaIntegration"></param>
        private void AfterListKeysDefaultImplementation(IListKeysApiResponse apiResponseLocalVar, Option<string> acceptLanguage, Option<string> xDonaIntegration)
        {
            bool suppressDefaultLog = false;
            AfterListKeys(ref suppressDefaultLog, apiResponseLocalVar, acceptLanguage, xDonaIntegration);
            if (!suppressDefaultLog)
                Logger.LogInformation(RestLogEvents.ApiRequestCompleted, "{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="acceptLanguage"></param>
        /// <param name="xDonaIntegration"></param>
        partial void AfterListKeys(ref bool suppressDefaultLog, IListKeysApiResponse apiResponseLocalVar, Option<string> acceptLanguage, Option<string> xDonaIntegration);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="acceptLanguage"></param>
        /// <param name="xDonaIntegration"></param>
        private void OnErrorListKeysDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<string> acceptLanguage, Option<string> xDonaIntegration)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorListKeys(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, acceptLanguage, xDonaIntegration);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(RestLogEvents.ApiRequestFailed, exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="acceptLanguage"></param>
        /// <param name="xDonaIntegration"></param>
        partial void OnErrorListKeys(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<string> acceptLanguage, Option<string> xDonaIntegration);

        /// <summary>
        /// The shop&#39;s keys (read-only; management is portal-only) Metadata only — never a secret, never &#x60;last_used_ip&#x60;. Mint/rotate/revoke live in the seller portal.
        /// </summary>
        /// <param name="acceptLanguage">Localises &#x60;message&#x60; in error bodies and single-language renderings. Default &#x60;uz&#x60;. (optional, default to &quot;uz&quot;)</param>
        /// <param name="xDonaIntegration">&#x60;name/version&#x60; of the calling integration; stored (≤ 128 chars) and searchable in the request journal. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListKeysApiResponse"/>&gt;</returns>
        public async Task<IListKeysApiResponse?> ListKeysOrDefaultAsync(Option<string> acceptLanguage = default, Option<string> xDonaIntegration = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await ListKeysAsync(acceptLanguage, xDonaIntegration, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// The shop&#39;s keys (read-only; management is portal-only) Metadata only — never a secret, never &#x60;last_used_ip&#x60;. Mint/rotate/revoke live in the seller portal.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="acceptLanguage">Localises &#x60;message&#x60; in error bodies and single-language renderings. Default &#x60;uz&#x60;. (optional, default to &quot;uz&quot;)</param>
        /// <param name="xDonaIntegration">&#x60;name/version&#x60; of the calling integration; stored (≤ 128 chars) and searchable in the request journal. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListKeysApiResponse"/>&gt;</returns>
        public async Task<IListKeysApiResponse> ListKeysAsync(Option<string> acceptLanguage = default, Option<string> xDonaIntegration = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateListKeys(acceptLanguage, xDonaIntegration);

                FormatListKeys(ref acceptLanguage, ref xDonaIntegration);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/keys"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/keys");

                    if (acceptLanguage.IsSet)
                    {
                      // Set client side default value of Header Param "Accept-Language".                    
                      if (ClientUtils.IsContentHeader("Accept-Language"))
                      {
                          httpRequestMessageLocalVar.Content?.Headers.Add("Accept-Language", ClientUtils.ParameterToString(acceptLanguage.Value));
                      }
                      else
                      {
                          httpRequestMessageLocalVar.Headers.Add("Accept-Language", ClientUtils.ParameterToString(acceptLanguage.Value));
                      }
                    }

                    if (xDonaIntegration.IsSet)
                    {
                      // Set client side default value of Header Param "X-Dona-Integration".                    
                      if (ClientUtils.IsContentHeader("X-Dona-Integration"))
                      {
                          httpRequestMessageLocalVar.Content?.Headers.Add("X-Dona-Integration", ClientUtils.ParameterToString(xDonaIntegration.Value));
                      }
                      else
                      {
                          httpRequestMessageLocalVar.Headers.Add("X-Dona-Integration", ClientUtils.ParameterToString(xDonaIntegration.Value));
                      }
                    }

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    BearerToken bearerTokenLocalVar1 = (BearerToken) await BearerTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(bearerTokenLocalVar1);

                    bearerTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ListKeysApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(Logger, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/keys", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterListKeysDefaultImplementation(apiResponseLocalVar, acceptLanguage, xDonaIntegration);

                        Events.ExecuteOnListKeys(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorListKeysDefaultImplementation(e, "/keys", uriBuilderLocalVar.Path, acceptLanguage, xDonaIntegration);
                Events.ExecuteOnErrorListKeys(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="ListKeysApiResponse"/>
        /// </summary>
        public partial class ListKeysApiResponse : Dona.Api.Client.ApiResponse, IListKeysApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<KeysApi> Logger { get; }

            /// <summary>
            /// The <see cref="ListKeysApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ListKeysApiResponse(ILogger<KeysApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="ListKeysApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ListKeysApiResponse(ILogger<KeysApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public Dona.Api.Model.KeyPage? Ok()
            {
                bool suppressDefault = false;
                Dona.Api.Model.KeyPage? result = null;
                OnOk(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultOk();
                return result;
            }

            private Dona.Api.Model.KeyPage? DefaultOk()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<Dona.Api.Model.KeyPage>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnOk(ref bool suppressDefault, ref Dona.Api.Model.KeyPage? result);

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out Dona.Api.Model.KeyPage? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 401 Unauthorized
            /// </summary>
            /// <returns></returns>
            public bool IsUnauthorized => 401 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 401 Unauthorized
            /// </summary>
            /// <returns></returns>
            public Dona.Api.Model.Error? Unauthorized()
            {
                bool suppressDefault = false;
                Dona.Api.Model.Error? result = null;
                OnUnauthorized(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultUnauthorized();
                return result;
            }

            private Dona.Api.Model.Error? DefaultUnauthorized()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsUnauthorized
                    ? System.Text.Json.JsonSerializer.Deserialize<Dona.Api.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnUnauthorized(ref bool suppressDefault, ref Dona.Api.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 401 Unauthorized and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnauthorized([NotNullWhen(true)]out Dona.Api.Model.Error? result)
            {
                result = null;

                try
                {
                    result = Unauthorized();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)401);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 403 Forbidden
            /// </summary>
            /// <returns></returns>
            public bool IsForbidden => 403 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 403 Forbidden
            /// </summary>
            /// <returns></returns>
            public Dona.Api.Model.Error? Forbidden()
            {
                bool suppressDefault = false;
                Dona.Api.Model.Error? result = null;
                OnForbidden(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultForbidden();
                return result;
            }

            private Dona.Api.Model.Error? DefaultForbidden()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsForbidden
                    ? System.Text.Json.JsonSerializer.Deserialize<Dona.Api.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnForbidden(ref bool suppressDefault, ref Dona.Api.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 403 Forbidden and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryForbidden([NotNullWhen(true)]out Dona.Api.Model.Error? result)
            {
                result = null;

                try
                {
                    result = Forbidden();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)403);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 429 TooManyRequests
            /// </summary>
            /// <returns></returns>
            public bool IsTooManyRequests => 429 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 429 TooManyRequests
            /// </summary>
            /// <returns></returns>
            public Dona.Api.Model.Error? TooManyRequests()
            {
                bool suppressDefault = false;
                Dona.Api.Model.Error? result = null;
                OnTooManyRequests(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultTooManyRequests();
                return result;
            }

            private Dona.Api.Model.Error? DefaultTooManyRequests()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsTooManyRequests
                    ? System.Text.Json.JsonSerializer.Deserialize<Dona.Api.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnTooManyRequests(ref bool suppressDefault, ref Dona.Api.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 429 TooManyRequests and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryTooManyRequests([NotNullWhen(true)]out Dona.Api.Model.Error? result)
            {
                result = null;

                try
                {
                    result = TooManyRequests();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)429);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public bool IsInternalServerError => 500 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public Dona.Api.Model.Error? InternalServerError()
            {
                bool suppressDefault = false;
                Dona.Api.Model.Error? result = null;
                OnInternalServerError(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultInternalServerError();
                return result;
            }

            private Dona.Api.Model.Error? DefaultInternalServerError()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsInternalServerError
                    ? System.Text.Json.JsonSerializer.Deserialize<Dona.Api.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnInternalServerError(ref bool suppressDefault, ref Dona.Api.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 500 InternalServerError and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryInternalServerError([NotNullWhen(true)]out Dona.Api.Model.Error? result)
            {
                result = null;

                try
                {
                    result = InternalServerError();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)500);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 503 ServiceUnavailable
            /// </summary>
            /// <returns></returns>
            public bool IsServiceUnavailable => 503 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 503 ServiceUnavailable
            /// </summary>
            /// <returns></returns>
            public Dona.Api.Model.Error? ServiceUnavailable()
            {
                bool suppressDefault = false;
                Dona.Api.Model.Error? result = null;
                OnServiceUnavailable(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultServiceUnavailable();
                return result;
            }

            private Dona.Api.Model.Error? DefaultServiceUnavailable()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsServiceUnavailable
                    ? System.Text.Json.JsonSerializer.Deserialize<Dona.Api.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnServiceUnavailable(ref bool suppressDefault, ref Dona.Api.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 503 ServiceUnavailable and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryServiceUnavailable([NotNullWhen(true)]out Dona.Api.Model.Error? result)
            {
                result = null;

                try
                {
                    result = ServiceUnavailable();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)503);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(RestLogEvents.ApiDeserializationFailed, exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
