<?php
/**
 * Commission
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dona\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Dona API
 *
 * Dona API v1 (https://api.dona.im/seller-api/v1) — client generated from the OpenAPI contract. Conventions (auth, errors, idempotency, dry_run, rate limits, 202 held_for_review): https://github.com/ozbuz/dona-api#readme · contract: https://api.dona.im/seller-api/v1/openapi.json
 *
 * The version of the OpenAPI document: v1 (frozen 2026-09-24)
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dona\Api\Model;

use \ArrayAccess;
use \Dona\Api\ObjectSerializer;

/**
 * Commission Class Doc Comment
 *
 * @category Class
 * @description The seller portal&#39;s &#x60;GET /seller/commission&#x60; body, byte for byte.
 * @package  Dona\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Commission implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'Commission';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'seller_id' => 'string',
        'default_pct' => 'float',
        'start_pct' => 'float',
        'roots' => '\Dona\Api\Model\CommissionRoot[]',
        'offer' => '\Dona\Api\Model\CommissionOffer',
        'saved_uzs' => 'int',
        'campaigns' => '\Dona\Api\Model\CommissionCampaign[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'seller_id' => 'uuid',
        'default_pct' => null,
        'start_pct' => null,
        'roots' => null,
        'offer' => null,
        'saved_uzs' => 'int64',
        'campaigns' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'seller_id' => false,
        'default_pct' => false,
        'start_pct' => false,
        'roots' => false,
        'offer' => true,
        'saved_uzs' => true,
        'campaigns' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'seller_id' => 'seller_id',
        'default_pct' => 'default_pct',
        'start_pct' => 'start_pct',
        'roots' => 'roots',
        'offer' => 'offer',
        'saved_uzs' => 'saved_uzs',
        'campaigns' => 'campaigns'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'seller_id' => 'setSellerId',
        'default_pct' => 'setDefaultPct',
        'start_pct' => 'setStartPct',
        'roots' => 'setRoots',
        'offer' => 'setOffer',
        'saved_uzs' => 'setSavedUzs',
        'campaigns' => 'setCampaigns'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'seller_id' => 'getSellerId',
        'default_pct' => 'getDefaultPct',
        'start_pct' => 'getStartPct',
        'roots' => 'getRoots',
        'offer' => 'getOffer',
        'saved_uzs' => 'getSavedUzs',
        'campaigns' => 'getCampaigns'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('seller_id', $data ?? [], null);
        $this->setIfExists('default_pct', $data ?? [], null);
        $this->setIfExists('start_pct', $data ?? [], null);
        $this->setIfExists('roots', $data ?? [], null);
        $this->setIfExists('offer', $data ?? [], null);
        $this->setIfExists('saved_uzs', $data ?? [], null);
        $this->setIfExists('campaigns', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['seller_id'] === null) {
            $invalidProperties[] = "'seller_id' can't be null";
        }
        if ($this->container['default_pct'] === null) {
            $invalidProperties[] = "'default_pct' can't be null";
        }
        if ($this->container['start_pct'] === null) {
            $invalidProperties[] = "'start_pct' can't be null";
        }
        if ($this->container['roots'] === null) {
            $invalidProperties[] = "'roots' can't be null";
        }
        if ($this->container['offer'] === null && !$this->isNullableSetToNull('offer')) {
            $invalidProperties[] = "'offer' is required";
        }
        if ($this->container['saved_uzs'] === null && !$this->isNullableSetToNull('saved_uzs')) {
            $invalidProperties[] = "'saved_uzs' is required";
        }
        if ($this->container['campaigns'] === null) {
            $invalidProperties[] = "'campaigns' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets seller_id
     *
     * @return string
     */
    public function getSellerId()
    {
        return $this->container['seller_id'];
    }

    /**
     * Sets seller_id
     *
     * @param string $seller_id seller_id
     *
     * @return self
     */
    public function setSellerId($seller_id)
    {
        if (is_null($seller_id)) {
            throw new \InvalidArgumentException('non-nullable seller_id cannot be null');
        }
        $this->container['seller_id'] = $seller_id;

        return $this;
    }

    /**
     * Gets default_pct
     *
     * @return float
     */
    public function getDefaultPct()
    {
        return $this->container['default_pct'];
    }

    /**
     * Sets default_pct
     *
     * @param float $default_pct The platform rate when a category tree carries none.
     *
     * @return self
     */
    public function setDefaultPct($default_pct)
    {
        if (is_null($default_pct)) {
            throw new \InvalidArgumentException('non-nullable default_pct cannot be null');
        }
        $this->container['default_pct'] = $default_pct;

        return $this;
    }

    /**
     * Gets start_pct
     *
     * @return float
     */
    public function getStartPct()
    {
        return $this->container['start_pct'];
    }

    /**
     * Sets start_pct
     *
     * @param float $start_pct The lowest rate on the card (MIN of `roots[].min_pct`; `default_pct` when there are no roots).
     *
     * @return self
     */
    public function setStartPct($start_pct)
    {
        if (is_null($start_pct)) {
            throw new \InvalidArgumentException('non-nullable start_pct cannot be null');
        }
        $this->container['start_pct'] = $start_pct;

        return $this;
    }

    /**
     * Gets roots
     *
     * @return \Dona\Api\Model\CommissionRoot[]
     */
    public function getRoots()
    {
        return $this->container['roots'];
    }

    /**
     * Sets roots
     *
     * @param \Dona\Api\Model\CommissionRoot[] $roots roots
     *
     * @return self
     */
    public function setRoots($roots)
    {
        if (is_null($roots)) {
            throw new \InvalidArgumentException('non-nullable roots cannot be null');
        }
        $this->container['roots'] = $roots;

        return $this;
    }

    /**
     * Gets offer
     *
     * @return \Dona\Api\Model\CommissionOffer|null
     */
    public function getOffer()
    {
        return $this->container['offer'];
    }

    /**
     * Sets offer
     *
     * @param \Dona\Api\Model\CommissionOffer|null $offer offer
     *
     * @return self
     */
    public function setOffer($offer)
    {
        if (is_null($offer)) {
            array_push($this->openAPINullablesSetToNull, 'offer');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('offer', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['offer'] = $offer;

        return $this;
    }

    /**
     * Gets saved_uzs
     *
     * @return int|null
     */
    public function getSavedUzs()
    {
        return $this->container['saved_uzs'];
    }

    /**
     * Sets saved_uzs
     *
     * @param int|null $saved_uzs What the launch offer and the commission campaigns spared this shop so far (orders not cancelled), in som, from the order-line snapshots only. A number while `offer.code` is `launch_v1` or the shop has a campaign-priced line; otherwise `null`.
     *
     * @return self
     */
    public function setSavedUzs($saved_uzs)
    {
        if (is_null($saved_uzs)) {
            array_push($this->openAPINullablesSetToNull, 'saved_uzs');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('saved_uzs', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['saved_uzs'] = $saved_uzs;

        return $this;
    }

    /**
     * Gets campaigns
     *
     * @return \Dona\Api\Model\CommissionCampaign[]
     */
    public function getCampaigns()
    {
        return $this->container['campaigns'];
    }

    /**
     * Sets campaigns
     *
     * @param \Dona\Api\Model\CommissionCampaign[] $campaigns Every promised or running grant whose campaign prices this shop now (a paused campaign disappears at once). Empty while campaigns do not apply to the shop.
     *
     * @return self
     */
    public function setCampaigns($campaigns)
    {
        if (is_null($campaigns)) {
            throw new \InvalidArgumentException('non-nullable campaigns cannot be null');
        }
        $this->container['campaigns'] = $campaigns;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


