<?php
/**
 * WebhookWithSecret
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dona\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Dona API
 *
 * Dona API v1 (https://api.dona.im/seller-api/v1) — client generated from the OpenAPI contract. Conventions (auth, errors, idempotency, dry_run, rate limits, 202 held_for_review): https://github.com/ozbuz/dona-api#readme · contract: https://api.dona.im/seller-api/v1/openapi.json
 *
 * The version of the OpenAPI document: v1 (frozen 2026-09-24)
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dona\Api\Model;

use \ArrayAccess;
use \Dona\Api\ObjectSerializer;

/**
 * WebhookWithSecret Class Doc Comment
 *
 * @category Class
 * @package  Dona\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class WebhookWithSecret implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'WebhookWithSecret';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'string',
        'url' => 'string',
        'event_types' => 'string[]',
        'status' => 'string',
        'failing_since' => '\DateTime',
        'disabled_reason' => 'string',
        'consecutive_failures' => 'int',
        'last_delivered_at' => '\DateTime',
        'success_rate_24h' => 'float',
        'secret_rotating_until' => '\DateTime',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'secret' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'url' => 'uri',
        'event_types' => null,
        'status' => null,
        'failing_since' => 'date-time',
        'disabled_reason' => null,
        'consecutive_failures' => null,
        'last_delivered_at' => 'date-time',
        'success_rate_24h' => null,
        'secret_rotating_until' => 'date-time',
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'secret' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'url' => false,
        'event_types' => false,
        'status' => false,
        'failing_since' => false,
        'disabled_reason' => false,
        'consecutive_failures' => false,
        'last_delivered_at' => false,
        'success_rate_24h' => false,
        'secret_rotating_until' => false,
        'created_at' => false,
        'updated_at' => false,
        'secret' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'url' => 'url',
        'event_types' => 'event_types',
        'status' => 'status',
        'failing_since' => 'failing_since',
        'disabled_reason' => 'disabled_reason',
        'consecutive_failures' => 'consecutive_failures',
        'last_delivered_at' => 'last_delivered_at',
        'success_rate_24h' => 'success_rate_24h',
        'secret_rotating_until' => 'secret_rotating_until',
        'created_at' => 'created_at',
        'updated_at' => 'updated_at',
        'secret' => 'secret'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'url' => 'setUrl',
        'event_types' => 'setEventTypes',
        'status' => 'setStatus',
        'failing_since' => 'setFailingSince',
        'disabled_reason' => 'setDisabledReason',
        'consecutive_failures' => 'setConsecutiveFailures',
        'last_delivered_at' => 'setLastDeliveredAt',
        'success_rate_24h' => 'setSuccessRate24h',
        'secret_rotating_until' => 'setSecretRotatingUntil',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'secret' => 'setSecret'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'url' => 'getUrl',
        'event_types' => 'getEventTypes',
        'status' => 'getStatus',
        'failing_since' => 'getFailingSince',
        'disabled_reason' => 'getDisabledReason',
        'consecutive_failures' => 'getConsecutiveFailures',
        'last_delivered_at' => 'getLastDeliveredAt',
        'success_rate_24h' => 'getSuccessRate24h',
        'secret_rotating_until' => 'getSecretRotatingUntil',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'secret' => 'getSecret'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('event_types', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('failing_since', $data ?? [], null);
        $this->setIfExists('disabled_reason', $data ?? [], null);
        $this->setIfExists('consecutive_failures', $data ?? [], null);
        $this->setIfExists('last_delivered_at', $data ?? [], null);
        $this->setIfExists('success_rate_24h', $data ?? [], null);
        $this->setIfExists('secret_rotating_until', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('secret', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['url'] === null) {
            $invalidProperties[] = "'url' can't be null";
        }
        if ($this->container['event_types'] === null) {
            $invalidProperties[] = "'event_types' can't be null";
        }
        if ((count($this->container['event_types']) < 1)) {
            $invalidProperties[] = "invalid value for 'event_types', number of items must be greater than or equal to 1.";
        }

        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['failing_since'] === null) {
            $invalidProperties[] = "'failing_since' can't be null";
        }
        if ($this->container['disabled_reason'] === null) {
            $invalidProperties[] = "'disabled_reason' can't be null";
        }
        if ($this->container['consecutive_failures'] === null) {
            $invalidProperties[] = "'consecutive_failures' can't be null";
        }
        if ($this->container['last_delivered_at'] === null) {
            $invalidProperties[] = "'last_delivered_at' can't be null";
        }
        if ($this->container['success_rate_24h'] === null) {
            $invalidProperties[] = "'success_rate_24h' can't be null";
        }
        if (($this->container['success_rate_24h'] > 1)) {
            $invalidProperties[] = "invalid value for 'success_rate_24h', must be smaller than or equal to 1.";
        }

        if (($this->container['success_rate_24h'] < 0)) {
            $invalidProperties[] = "invalid value for 'success_rate_24h', must be bigger than or equal to 0.";
        }

        if ($this->container['secret_rotating_until'] === null) {
            $invalidProperties[] = "'secret_rotating_until' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['updated_at'] === null) {
            $invalidProperties[] = "'updated_at' can't be null";
        }
        if ($this->container['secret'] === null && !$this->isNullableSetToNull('secret')) {
            $invalidProperties[] = "'secret' is required";
        }
        if (!is_null($this->container['secret']) && !preg_match("/^whsec_/", $this->container['secret'])) {
            $invalidProperties[] = "invalid value for 'secret', must be conform to the pattern /^whsec_/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url url
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets event_types
     *
     * @return string[]
     */
    public function getEventTypes()
    {
        return $this->container['event_types'];
    }

    /**
     * Sets event_types
     *
     * @param string[] $event_types Exact event names or prefixes (`order.*`); `[\"*\"]` (or omitted on create) = every event.
     *
     * @return self
     */
    public function setEventTypes($event_types)
    {
        if (is_null($event_types)) {
            throw new \InvalidArgumentException('non-nullable event_types cannot be null');
        }

        if ((count($event_types) < 1)) {
            throw new \InvalidArgumentException('invalid length for $event_types when calling WebhookWithSecret., number of items must be greater than or equal to 1.');
        }
        $this->container['event_types'] = $event_types;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status Known values (open set — tolerate new ones): `active`, `paused`, `disabled`.
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets failing_since
     *
     * @return \DateTime
     */
    public function getFailingSince()
    {
        return $this->container['failing_since'];
    }

    /**
     * Sets failing_since
     *
     * @param \DateTime $failing_since failing_since
     *
     * @return self
     */
    public function setFailingSince($failing_since)
    {
        if (is_null($failing_since)) {
            throw new \InvalidArgumentException('non-nullable failing_since cannot be null');
        }
        $this->container['failing_since'] = $failing_since;

        return $this;
    }

    /**
     * Gets disabled_reason
     *
     * @return string
     */
    public function getDisabledReason()
    {
        return $this->container['disabled_reason'];
    }

    /**
     * Sets disabled_reason
     *
     * @param string $disabled_reason Known values (open set — tolerate new ones): `ladder_exhausted`, `success_rate`, `owner`, `staff`, `ssrf_recheck`.
     *
     * @return self
     */
    public function setDisabledReason($disabled_reason)
    {
        if (is_null($disabled_reason)) {
            throw new \InvalidArgumentException('non-nullable disabled_reason cannot be null');
        }
        $this->container['disabled_reason'] = $disabled_reason;

        return $this;
    }

    /**
     * Gets consecutive_failures
     *
     * @return int
     */
    public function getConsecutiveFailures()
    {
        return $this->container['consecutive_failures'];
    }

    /**
     * Sets consecutive_failures
     *
     * @param int $consecutive_failures consecutive_failures
     *
     * @return self
     */
    public function setConsecutiveFailures($consecutive_failures)
    {
        if (is_null($consecutive_failures)) {
            throw new \InvalidArgumentException('non-nullable consecutive_failures cannot be null');
        }
        $this->container['consecutive_failures'] = $consecutive_failures;

        return $this;
    }

    /**
     * Gets last_delivered_at
     *
     * @return \DateTime
     */
    public function getLastDeliveredAt()
    {
        return $this->container['last_delivered_at'];
    }

    /**
     * Sets last_delivered_at
     *
     * @param \DateTime $last_delivered_at last_delivered_at
     *
     * @return self
     */
    public function setLastDeliveredAt($last_delivered_at)
    {
        if (is_null($last_delivered_at)) {
            throw new \InvalidArgumentException('non-nullable last_delivered_at cannot be null');
        }
        $this->container['last_delivered_at'] = $last_delivered_at;

        return $this;
    }

    /**
     * Gets success_rate_24h
     *
     * @return float
     */
    public function getSuccessRate24h()
    {
        return $this->container['success_rate_24h'];
    }

    /**
     * Sets success_rate_24h
     *
     * @param float $success_rate_24h success_rate_24h
     *
     * @return self
     */
    public function setSuccessRate24h($success_rate_24h)
    {
        if (is_null($success_rate_24h)) {
            throw new \InvalidArgumentException('non-nullable success_rate_24h cannot be null');
        }
        if (($success_rate_24h > 1)) {
            throw new \InvalidArgumentException('invalid value for $success_rate_24h when calling WebhookWithSecret., must be smaller than or equal to 1.');
        }
        if (($success_rate_24h < 0)) {
            throw new \InvalidArgumentException('invalid value for $success_rate_24h when calling WebhookWithSecret., must be bigger than or equal to 0.');
        }

        $this->container['success_rate_24h'] = $success_rate_24h;

        return $this;
    }

    /**
     * Gets secret_rotating_until
     *
     * @return \DateTime
     */
    public function getSecretRotatingUntil()
    {
        return $this->container['secret_rotating_until'];
    }

    /**
     * Sets secret_rotating_until
     *
     * @param \DateTime $secret_rotating_until While set, deliveries carry two signatures.
     *
     * @return self
     */
    public function setSecretRotatingUntil($secret_rotating_until)
    {
        if (is_null($secret_rotating_until)) {
            throw new \InvalidArgumentException('non-nullable secret_rotating_until cannot be null');
        }
        $this->container['secret_rotating_until'] = $secret_rotating_until;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at ISO 8601 with offset (Tashkent `+05:00` on output).
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime $updated_at ISO 8601 with offset (Tashkent `+05:00` on output).
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets secret
     *
     * @return string|null
     */
    public function getSecret()
    {
        return $this->container['secret'];
    }

    /**
     * Sets secret
     *
     * @param string|null $secret `whsec_…` — shown ONCE. An idempotent replay of this call returns `null`: the secret is never stored in the replay table.
     *
     * @return self
     */
    public function setSecret($secret)
    {
        if (is_null($secret)) {
            array_push($this->openAPINullablesSetToNull, 'secret');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('secret', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($secret) && (!preg_match("/^whsec_/", ObjectSerializer::toString($secret)))) {
            throw new \InvalidArgumentException("invalid value for \$secret when calling WebhookWithSecret., must conform to the pattern /^whsec_/.");
        }

        $this->container['secret'] = $secret;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


