// <auto-generated>
/*
 * Dona API
 *
 * Dona API v1 (https://api.dona.im/seller-api/v1) — client generated from the OpenAPI contract. Conventions (auth, errors, idempotency, dry_run, rate limits, 202 held_for_review): https://github.com/ozbuz/dona-api#readme · contract: https://api.dona.im/seller-api/v1/openapi.json
 *
 * The version of the OpenAPI document: v1 (frozen 2026-09-24)
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using Dona.Api.Client;

namespace Dona.Api.Model
{
    /// <summary>
    /// AccountStatusEventData
    /// </summary>
    public partial class AccountStatusEventData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountStatusEventData" /> class.
        /// </summary>
        /// <param name="status">status</param>
        /// <param name="canSell">canSell</param>
        /// <param name="actionUrl">actionUrl</param>
        /// <param name="reasonCode">reasonCode</param>
        [JsonConstructor]
        public AccountStatusEventData(string status, bool canSell, string actionUrl, Option<string?> reasonCode = default)
        {
            Status = status;
            CanSell = canSell;
            ActionUrl = actionUrl;
            ReasonCodeOption = reasonCode;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets CanSell
        /// </summary>
        [JsonPropertyName("can_sell")]
        public bool CanSell { get; set; }

        /// <summary>
        /// Gets or Sets ActionUrl
        /// </summary>
        [JsonPropertyName("action_url")]
        public string ActionUrl { get; set; }

        /// <summary>
        /// Used to track the state of ReasonCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ReasonCodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReasonCode
        /// </summary>
        [JsonPropertyName("reason_code")]
        public string? ReasonCode { get { return this.ReasonCodeOption.Value; } set { this.ReasonCodeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AccountStatusEventData {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CanSell: ").Append(CanSell).Append("\n");
            sb.Append("  ActionUrl: ").Append(ActionUrl).Append("\n");
            sb.Append("  ReasonCode: ").Append(ReasonCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AccountStatusEventData" />
    /// </summary>
    public partial class AccountStatusEventDataJsonConverter : JsonConverter<AccountStatusEventData>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountStatusEventDataJsonConverter" /> class.
        /// </summary>
        public AccountStatusEventDataJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="AccountStatusEventData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AccountStatusEventData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> status = default;
            Option<bool?> canSell = default;
            Option<string?> actionUrl = default;
            Option<string?> reasonCode = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "can_sell":
                            canSell = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "action_url":
                            actionUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "reason_code":
                            reasonCode = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class AccountStatusEventData.", nameof(status));

            if (!canSell.IsSet)
                throw new ArgumentException("Property is required for class AccountStatusEventData.", nameof(canSell));

            if (!actionUrl.IsSet)
                throw new ArgumentException("Property is required for class AccountStatusEventData.", nameof(actionUrl));

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class AccountStatusEventData.");

            if (canSell.IsSet && canSell.Value == null)
                throw new ArgumentNullException(nameof(canSell), "Property is not nullable for class AccountStatusEventData.");

            if (actionUrl.IsSet && actionUrl.Value == null)
                throw new ArgumentNullException(nameof(actionUrl), "Property is not nullable for class AccountStatusEventData.");

            return new AccountStatusEventData(status.Value!, canSell.Value!.Value!, actionUrl.Value!, reasonCode);
        }

        /// <summary>
        /// Serializes a <see cref="AccountStatusEventData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="accountStatusEventData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AccountStatusEventData accountStatusEventData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, accountStatusEventData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AccountStatusEventData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="accountStatusEventData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AccountStatusEventData accountStatusEventData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (accountStatusEventData.Status == null)
                throw new ArgumentNullException(nameof(accountStatusEventData.Status), "Property is required for class AccountStatusEventData.");

            if (accountStatusEventData.ActionUrl == null)
                throw new ArgumentNullException(nameof(accountStatusEventData.ActionUrl), "Property is required for class AccountStatusEventData.");

            writer.WriteString("status", accountStatusEventData.Status);

            writer.WriteBoolean("can_sell", accountStatusEventData.CanSell);

            writer.WriteString("action_url", accountStatusEventData.ActionUrl);

            if (accountStatusEventData.ReasonCodeOption.IsSet)
                if (accountStatusEventData.ReasonCodeOption.Value != null)
                    writer.WriteString("reason_code", accountStatusEventData.ReasonCode);
                else
                    writer.WriteNull("reason_code");
        }
    }
}
