// <auto-generated>
/*
 * Dona API
 *
 * Dona API v1 (https://api.dona.im/seller-api/v1) — client generated from the OpenAPI contract. Conventions (auth, errors, idempotency, dry_run, rate limits, 202 held_for_review): https://github.com/ozbuz/dona-api#readme · contract: https://api.dona.im/seller-api/v1/openapi.json
 *
 * The version of the OpenAPI document: v1 (frozen 2026-09-24)
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using Dona.Api.Client;

namespace Dona.Api.Model
{
    /// <summary>
    /// BulkResultSummary
    /// </summary>
    public partial class BulkResultSummary
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkResultSummary" /> class.
        /// </summary>
        /// <param name="ok">ok</param>
        /// <param name="error">error</param>
        /// <param name="held">held</param>
        [JsonConstructor]
        public BulkResultSummary(int ok, int error, int held)
        {
            Ok = ok;
            Error = error;
            Held = held;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Ok
        /// </summary>
        [JsonPropertyName("ok")]
        public int Ok { get; set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [JsonPropertyName("error")]
        public int Error { get; set; }

        /// <summary>
        /// Gets or Sets Held
        /// </summary>
        [JsonPropertyName("held")]
        public int Held { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BulkResultSummary {\n");
            sb.Append("  Ok: ").Append(Ok).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  Held: ").Append(Held).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BulkResultSummary" />
    /// </summary>
    public partial class BulkResultSummaryJsonConverter : JsonConverter<BulkResultSummary>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="BulkResultSummaryJsonConverter" /> class.
        /// </summary>
        public BulkResultSummaryJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="BulkResultSummary" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BulkResultSummary Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> ok = default;
            Option<int?> error = default;
            Option<int?> held = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "ok":
                            ok = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "error":
                            error = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "held":
                            held = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!ok.IsSet)
                throw new ArgumentException("Property is required for class BulkResultSummary.", nameof(ok));

            if (!error.IsSet)
                throw new ArgumentException("Property is required for class BulkResultSummary.", nameof(error));

            if (!held.IsSet)
                throw new ArgumentException("Property is required for class BulkResultSummary.", nameof(held));

            if (ok.IsSet && ok.Value == null)
                throw new ArgumentNullException(nameof(ok), "Property is not nullable for class BulkResultSummary.");

            if (error.IsSet && error.Value == null)
                throw new ArgumentNullException(nameof(error), "Property is not nullable for class BulkResultSummary.");

            if (held.IsSet && held.Value == null)
                throw new ArgumentNullException(nameof(held), "Property is not nullable for class BulkResultSummary.");

            return new BulkResultSummary(ok.Value!.Value!, error.Value!.Value!, held.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="BulkResultSummary" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="bulkResultSummary"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BulkResultSummary bulkResultSummary, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, bulkResultSummary, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BulkResultSummary" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="bulkResultSummary"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, BulkResultSummary bulkResultSummary, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("ok", bulkResultSummary.Ok);

            writer.WriteNumber("error", bulkResultSummary.Error);

            writer.WriteNumber("held", bulkResultSummary.Held);
        }
    }
}
