// <auto-generated>
/*
 * Dona API
 *
 * Dona API v1 (https://api.dona.im/seller-api/v1) — client generated from the OpenAPI contract. Conventions (auth, errors, idempotency, dry_run, rate limits, 202 held_for_review): https://github.com/ozbuz/dona-api#readme · contract: https://api.dona.im/seller-api/v1/openapi.json
 *
 * The version of the OpenAPI document: v1 (frozen 2026-09-24)
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using Dona.Api.Client;

namespace Dona.Api.Model
{
    /// <summary>
    /// DeclineRequest
    /// </summary>
    public partial class DeclineRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DeclineRequest" /> class.
        /// </summary>
        /// <param name="reason">Uzum subset (&#x60;OUT_OF_STOCK&#x60;, &#x60;OUT_OF_PACKAGE&#x60;, &#x60;OUT_OF_TIME&#x60;, &#x60;OTHER&#x60;) mapped onto the native &#x60;declineReasons&#x60;, OR a native lowercase code. &#x60;OTHER&#x60;/&#x60;other&#x60; needs &#x60;comment&#x60;. Unknown ⇒ &#x60;400 invalid_decline_reason&#x60;. Known values (open set — tolerate new ones): &#x60;OUT_OF_STOCK&#x60;, &#x60;OUT_OF_PACKAGE&#x60;, &#x60;OUT_OF_TIME&#x60;, &#x60;OTHER&#x60;, &#x60;out_of_stock&#x60;, &#x60;inventory_mismatch&#x60;, &#x60;product_damaged&#x60;, &#x60;store_unavailable&#x60;, &#x60;cannot_fulfill_in_time&#x60;, &#x60;duplicate_order&#x60;, &#x60;fraud_suspected&#x60;, &#x60;other&#x60;.</param>
        /// <param name="comment">comment</param>
        [JsonConstructor]
        public DeclineRequest(string reason, Option<string?> comment = default)
        {
            Reason = reason;
            CommentOption = comment;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Uzum subset (&#x60;OUT_OF_STOCK&#x60;, &#x60;OUT_OF_PACKAGE&#x60;, &#x60;OUT_OF_TIME&#x60;, &#x60;OTHER&#x60;) mapped onto the native &#x60;declineReasons&#x60;, OR a native lowercase code. &#x60;OTHER&#x60;/&#x60;other&#x60; needs &#x60;comment&#x60;. Unknown ⇒ &#x60;400 invalid_decline_reason&#x60;. Known values (open set — tolerate new ones): &#x60;OUT_OF_STOCK&#x60;, &#x60;OUT_OF_PACKAGE&#x60;, &#x60;OUT_OF_TIME&#x60;, &#x60;OTHER&#x60;, &#x60;out_of_stock&#x60;, &#x60;inventory_mismatch&#x60;, &#x60;product_damaged&#x60;, &#x60;store_unavailable&#x60;, &#x60;cannot_fulfill_in_time&#x60;, &#x60;duplicate_order&#x60;, &#x60;fraud_suspected&#x60;, &#x60;other&#x60;.
        /// </summary>
        /// <value>Uzum subset (&#x60;OUT_OF_STOCK&#x60;, &#x60;OUT_OF_PACKAGE&#x60;, &#x60;OUT_OF_TIME&#x60;, &#x60;OTHER&#x60;) mapped onto the native &#x60;declineReasons&#x60;, OR a native lowercase code. &#x60;OTHER&#x60;/&#x60;other&#x60; needs &#x60;comment&#x60;. Unknown ⇒ &#x60;400 invalid_decline_reason&#x60;. Known values (open set — tolerate new ones): &#x60;OUT_OF_STOCK&#x60;, &#x60;OUT_OF_PACKAGE&#x60;, &#x60;OUT_OF_TIME&#x60;, &#x60;OTHER&#x60;, &#x60;out_of_stock&#x60;, &#x60;inventory_mismatch&#x60;, &#x60;product_damaged&#x60;, &#x60;store_unavailable&#x60;, &#x60;cannot_fulfill_in_time&#x60;, &#x60;duplicate_order&#x60;, &#x60;fraud_suspected&#x60;, &#x60;other&#x60;.</value>
        [JsonPropertyName("reason")]
        public string Reason { get; set; }

        /// <summary>
        /// Used to track the state of Comment
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CommentOption { get; private set; }

        /// <summary>
        /// Gets or Sets Comment
        /// </summary>
        [JsonPropertyName("comment")]
        public string? Comment { get { return this.CommentOption.Value; } set { this.CommentOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DeclineRequest {\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DeclineRequest" />
    /// </summary>
    public partial class DeclineRequestJsonConverter : JsonConverter<DeclineRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="DeclineRequestJsonConverter" /> class.
        /// </summary>
        public DeclineRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="DeclineRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DeclineRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> reason = default;
            Option<string?> comment = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "reason":
                            reason = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "comment":
                            comment = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!reason.IsSet)
                throw new ArgumentException("Property is required for class DeclineRequest.", nameof(reason));

            if (reason.IsSet && reason.Value == null)
                throw new ArgumentNullException(nameof(reason), "Property is not nullable for class DeclineRequest.");

            if (comment.IsSet && comment.Value == null)
                throw new ArgumentNullException(nameof(comment), "Property is not nullable for class DeclineRequest.");

            return new DeclineRequest(reason.Value!, comment);
        }

        /// <summary>
        /// Serializes a <see cref="DeclineRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="declineRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DeclineRequest declineRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, declineRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DeclineRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="declineRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DeclineRequest declineRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (declineRequest.Reason == null)
                throw new ArgumentNullException(nameof(declineRequest.Reason), "Property is required for class DeclineRequest.");

            if (declineRequest.CommentOption.IsSet && declineRequest.Comment == null)
                throw new ArgumentNullException(nameof(declineRequest.Comment), "Property is required for class DeclineRequest.");

            writer.WriteString("reason", declineRequest.Reason);

            if (declineRequest.CommentOption.IsSet)
                writer.WriteString("comment", declineRequest.Comment);
        }
    }
}
