// <auto-generated>
/*
 * Dona API
 *
 * Dona API v1 (https://api.dona.im/seller-api/v1) — client generated from the OpenAPI contract. Conventions (auth, errors, idempotency, dry_run, rate limits, 202 held_for_review): https://github.com/ozbuz/dona-api#readme · contract: https://api.dona.im/seller-api/v1/openapi.json
 *
 * The version of the OpenAPI document: v1 (frozen 2026-09-24)
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using Dona.Api.Client;

namespace Dona.Api.Model
{
    /// <summary>
    /// IkpuPackagesInner
    /// </summary>
    public partial class IkpuPackagesInner
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IkpuPackagesInner" /> class.
        /// </summary>
        /// <param name="code">code</param>
        /// <param name="name">name</param>
        [JsonConstructor]
        public IkpuPackagesInner(string code, string name)
        {
            Code = code;
            Name = name;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [JsonPropertyName("code")]
        public string Code { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IkpuPackagesInner {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="IkpuPackagesInner" />
    /// </summary>
    public partial class IkpuPackagesInnerJsonConverter : JsonConverter<IkpuPackagesInner>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="IkpuPackagesInnerJsonConverter" /> class.
        /// </summary>
        public IkpuPackagesInnerJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="IkpuPackagesInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override IkpuPackagesInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> code = default;
            Option<string?> name = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "code":
                            code = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!code.IsSet)
                throw new ArgumentException("Property is required for class IkpuPackagesInner.", nameof(code));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class IkpuPackagesInner.", nameof(name));

            if (code.IsSet && code.Value == null)
                throw new ArgumentNullException(nameof(code), "Property is not nullable for class IkpuPackagesInner.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class IkpuPackagesInner.");

            return new IkpuPackagesInner(code.Value!, name.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="IkpuPackagesInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ikpuPackagesInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, IkpuPackagesInner ikpuPackagesInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, ikpuPackagesInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="IkpuPackagesInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ikpuPackagesInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, IkpuPackagesInner ikpuPackagesInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (ikpuPackagesInner.Code == null)
                throw new ArgumentNullException(nameof(ikpuPackagesInner.Code), "Property is required for class IkpuPackagesInner.");

            if (ikpuPackagesInner.Name == null)
                throw new ArgumentNullException(nameof(ikpuPackagesInner.Name), "Property is required for class IkpuPackagesInner.");

            writer.WriteString("code", ikpuPackagesInner.Code);

            writer.WriteString("name", ikpuPackagesInner.Name);
        }
    }
}
