// <auto-generated>
/*
 * Dona API
 *
 * Dona API v1 (https://api.dona.im/seller-api/v1) — client generated from the OpenAPI contract. Conventions (auth, errors, idempotency, dry_run, rate limits, 202 held_for_review): https://github.com/ozbuz/dona-api#readme · contract: https://api.dona.im/seller-api/v1/openapi.json
 *
 * The version of the OpenAPI document: v1 (frozen 2026-09-24)
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using Dona.Api.Client;

namespace Dona.Api.Model
{
    /// <summary>
    /// Issue
    /// </summary>
    public partial class Issue
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Issue" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="source">Known values (open set — tolerate new ones): &#x60;listing_issue&#x60;, &#x60;violation&#x60;, &#x60;shop_hold&#x60;.</param>
        /// <param name="severity">Known values (open set — tolerate new ones): &#x60;error&#x60;, &#x60;warning&#x60;.</param>
        /// <param name="type">type</param>
        /// <param name="createdAt">ISO 8601 with offset (Tashkent &#x60;+05:00&#x60; on output).</param>
        /// <param name="field">field</param>
        /// <param name="detail">detail</param>
        [JsonConstructor]
        public Issue(Guid id, string source, string severity, string type, DateTimeOffset createdAt, string? field = default, string? detail = default)
        {
            Id = id;
            Source = source;
            Severity = severity;
            Type = type;
            CreatedAt = createdAt;
            Field = field;
            Detail = detail;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Known values (open set — tolerate new ones): &#x60;listing_issue&#x60;, &#x60;violation&#x60;, &#x60;shop_hold&#x60;.
        /// </summary>
        /// <value>Known values (open set — tolerate new ones): &#x60;listing_issue&#x60;, &#x60;violation&#x60;, &#x60;shop_hold&#x60;.</value>
        [JsonPropertyName("source")]
        public string Source { get; set; }

        /// <summary>
        /// Known values (open set — tolerate new ones): &#x60;error&#x60;, &#x60;warning&#x60;.
        /// </summary>
        /// <value>Known values (open set — tolerate new ones): &#x60;error&#x60;, &#x60;warning&#x60;.</value>
        [JsonPropertyName("severity")]
        public string Severity { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public string Type { get; set; }

        /// <summary>
        /// ISO 8601 with offset (Tashkent &#x60;+05:00&#x60; on output).
        /// </summary>
        /// <value>ISO 8601 with offset (Tashkent &#x60;+05:00&#x60; on output).</value>
        [JsonPropertyName("created_at")]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets Field
        /// </summary>
        [JsonPropertyName("field")]
        public string? Field { get; set; }

        /// <summary>
        /// Gets or Sets Detail
        /// </summary>
        [JsonPropertyName("detail")]
        public string? Detail { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Issue {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("  Severity: ").Append(Severity).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Field: ").Append(Field).Append("\n");
            sb.Append("  Detail: ").Append(Detail).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Issue" />
    /// </summary>
    public partial class IssueJsonConverter : JsonConverter<Issue>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="IssueJsonConverter" /> class.
        /// </summary>
        public IssueJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public string CreatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="Issue" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Issue Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<string?> source = default;
            Option<string?> severity = default;
            Option<string?> type = default;
            Option<DateTimeOffset?> createdAt = default;
            Option<string?> field = default;
            Option<string?> detail = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "source":
                            source = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "severity":
                            severity = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "type":
                            type = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "created_at":
                            createdAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "field":
                            field = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "detail":
                            detail = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class Issue.", nameof(id));

            if (!source.IsSet)
                throw new ArgumentException("Property is required for class Issue.", nameof(source));

            if (!severity.IsSet)
                throw new ArgumentException("Property is required for class Issue.", nameof(severity));

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class Issue.", nameof(type));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class Issue.", nameof(createdAt));

            if (!field.IsSet)
                throw new ArgumentException("Property is required for class Issue.", nameof(field));

            if (!detail.IsSet)
                throw new ArgumentException("Property is required for class Issue.", nameof(detail));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Issue.");

            if (source.IsSet && source.Value == null)
                throw new ArgumentNullException(nameof(source), "Property is not nullable for class Issue.");

            if (severity.IsSet && severity.Value == null)
                throw new ArgumentNullException(nameof(severity), "Property is not nullable for class Issue.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class Issue.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class Issue.");

            return new Issue(id.Value!.Value!, source.Value!, severity.Value!, type.Value!, createdAt.Value!.Value!, field.Value!, detail.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="Issue" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="issue"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Issue issue, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, issue, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Issue" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="issue"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Issue issue, JsonSerializerOptions jsonSerializerOptions)
        {
            if (issue.Source == null)
                throw new ArgumentNullException(nameof(issue.Source), "Property is required for class Issue.");

            if (issue.Severity == null)
                throw new ArgumentNullException(nameof(issue.Severity), "Property is required for class Issue.");

            if (issue.Type == null)
                throw new ArgumentNullException(nameof(issue.Type), "Property is required for class Issue.");

            writer.WriteString("id", issue.Id);

            writer.WriteString("source", issue.Source);

            writer.WriteString("severity", issue.Severity);

            writer.WriteString("type", issue.Type);

            writer.WriteString("created_at", issue.CreatedAt.ToString(CreatedAtFormat));

            if (issue.Field != null)
                writer.WriteString("field", issue.Field);
            else
                writer.WriteNull("field");

            if (issue.Detail != null)
                writer.WriteString("detail", issue.Detail);
            else
                writer.WriteNull("detail");
        }
    }
}
