// <auto-generated>
/*
 * Dona API
 *
 * Dona API v1 (https://api.dona.im/seller-api/v1) — client generated from the OpenAPI contract. Conventions (auth, errors, idempotency, dry_run, rate limits, 202 held_for_review): https://github.com/ozbuz/dona-api#readme · contract: https://api.dona.im/seller-api/v1/openapi.json
 *
 * The version of the OpenAPI document: v1 (frozen 2026-09-24)
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using Dona.Api.Client;

namespace Dona.Api.Model
{
    /// <summary>
    /// Job
    /// </summary>
    public partial class Job
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Job" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="kind">Known values (open set — tolerate new ones): &#x60;export_products&#x60;, &#x60;export_orders&#x60;, &#x60;products_batch&#x60;.</param>
        /// <param name="status">Known values (open set — tolerate new ones): &#x60;pending&#x60;, &#x60;running&#x60;, &#x60;ready&#x60;, &#x60;failed&#x60;.</param>
        /// <param name="progress">progress</param>
        /// <param name="createdAt">ISO 8601 with offset (Tashkent &#x60;+05:00&#x60; on output).</param>
        /// <param name="expiresAt">Row + file swept after this (7 d); then &#x60;404 not_found&#x60;.</param>
        /// <param name="fileUrl">&#x60;GET /jobs/{id}/download?token&#x3D;…&#x60; — the token is valid 15 min from this response and only for a key of this shop (never a public or pre-signed object URL); re-read the job for a fresh one.</param>
        /// <param name="fileExpiresAt">fileExpiresAt</param>
        /// <param name="results">&#x60;products_batch&#x60; only: the per-line shape.</param>
        /// <param name="error">Our code only.</param>
        /// <param name="finishedAt">finishedAt</param>
        [JsonConstructor]
        public Job(Guid id, string kind, string status, JobProgress progress, DateTimeOffset createdAt, DateTimeOffset expiresAt, string? fileUrl = default, DateTimeOffset? fileExpiresAt = default, List<LineResult>? results = default, string? error = default, DateTimeOffset? finishedAt = default)
        {
            Id = id;
            Kind = kind;
            Status = status;
            Progress = progress;
            CreatedAt = createdAt;
            ExpiresAt = expiresAt;
            FileUrl = fileUrl;
            FileExpiresAt = fileExpiresAt;
            Results = results;
            Error = error;
            FinishedAt = finishedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Known values (open set — tolerate new ones): &#x60;export_products&#x60;, &#x60;export_orders&#x60;, &#x60;products_batch&#x60;.
        /// </summary>
        /// <value>Known values (open set — tolerate new ones): &#x60;export_products&#x60;, &#x60;export_orders&#x60;, &#x60;products_batch&#x60;.</value>
        [JsonPropertyName("kind")]
        public string Kind { get; set; }

        /// <summary>
        /// Known values (open set — tolerate new ones): &#x60;pending&#x60;, &#x60;running&#x60;, &#x60;ready&#x60;, &#x60;failed&#x60;.
        /// </summary>
        /// <value>Known values (open set — tolerate new ones): &#x60;pending&#x60;, &#x60;running&#x60;, &#x60;ready&#x60;, &#x60;failed&#x60;.</value>
        [JsonPropertyName("status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets Progress
        /// </summary>
        [JsonPropertyName("progress")]
        public JobProgress Progress { get; set; }

        /// <summary>
        /// ISO 8601 with offset (Tashkent &#x60;+05:00&#x60; on output).
        /// </summary>
        /// <value>ISO 8601 with offset (Tashkent &#x60;+05:00&#x60; on output).</value>
        [JsonPropertyName("created_at")]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// Row + file swept after this (7 d); then &#x60;404 not_found&#x60;.
        /// </summary>
        /// <value>Row + file swept after this (7 d); then &#x60;404 not_found&#x60;.</value>
        [JsonPropertyName("expires_at")]
        public DateTimeOffset ExpiresAt { get; set; }

        /// <summary>
        /// &#x60;GET /jobs/{id}/download?token&#x3D;…&#x60; — the token is valid 15 min from this response and only for a key of this shop (never a public or pre-signed object URL); re-read the job for a fresh one.
        /// </summary>
        /// <value>&#x60;GET /jobs/{id}/download?token&#x3D;…&#x60; — the token is valid 15 min from this response and only for a key of this shop (never a public or pre-signed object URL); re-read the job for a fresh one.</value>
        [JsonPropertyName("file_url")]
        public string? FileUrl { get; set; }

        /// <summary>
        /// Gets or Sets FileExpiresAt
        /// </summary>
        [JsonPropertyName("file_expires_at")]
        public DateTimeOffset? FileExpiresAt { get; set; }

        /// <summary>
        /// &#x60;products_batch&#x60; only: the per-line shape.
        /// </summary>
        /// <value>&#x60;products_batch&#x60; only: the per-line shape.</value>
        [JsonPropertyName("results")]
        public List<LineResult>? Results { get; set; }

        /// <summary>
        /// Our code only.
        /// </summary>
        /// <value>Our code only.</value>
        [JsonPropertyName("error")]
        public string? Error { get; set; }

        /// <summary>
        /// Gets or Sets FinishedAt
        /// </summary>
        [JsonPropertyName("finished_at")]
        public DateTimeOffset? FinishedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Job {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Kind: ").Append(Kind).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Progress: ").Append(Progress).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  ExpiresAt: ").Append(ExpiresAt).Append("\n");
            sb.Append("  FileUrl: ").Append(FileUrl).Append("\n");
            sb.Append("  FileExpiresAt: ").Append(FileExpiresAt).Append("\n");
            sb.Append("  Results: ").Append(Results).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  FinishedAt: ").Append(FinishedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Job" />
    /// </summary>
    public partial class JobJsonConverter : JsonConverter<Job>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="JobJsonConverter" /> class.
        /// </summary>
        public JobJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public string CreatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize ExpiresAt
        /// </summary>
        public string ExpiresAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize FileExpiresAt
        /// </summary>
        public string FileExpiresAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize FinishedAt
        /// </summary>
        public string FinishedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="Job" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Job Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<string?> kind = default;
            Option<string?> status = default;
            Option<JobProgress?> progress = default;
            Option<DateTimeOffset?> createdAt = default;
            Option<DateTimeOffset?> expiresAt = default;
            Option<string?> fileUrl = default;
            Option<DateTimeOffset?> fileExpiresAt = default;
            Option<List<LineResult>?> results = default;
            Option<string?> error = default;
            Option<DateTimeOffset?> finishedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "kind":
                            kind = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "progress":
                            progress = new Option<JobProgress?>(JsonSerializer.Deserialize<JobProgress>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "created_at":
                            createdAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "expires_at":
                            expiresAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "file_url":
                            fileUrl = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "file_expires_at":
                            fileExpiresAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "results":
                            results = new Option<List<LineResult>?>(JsonSerializer.Deserialize<List<LineResult>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "error":
                            error = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "finished_at":
                            finishedAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class Job.", nameof(id));

            if (!kind.IsSet)
                throw new ArgumentException("Property is required for class Job.", nameof(kind));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class Job.", nameof(status));

            if (!progress.IsSet)
                throw new ArgumentException("Property is required for class Job.", nameof(progress));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class Job.", nameof(createdAt));

            if (!expiresAt.IsSet)
                throw new ArgumentException("Property is required for class Job.", nameof(expiresAt));

            if (!fileUrl.IsSet)
                throw new ArgumentException("Property is required for class Job.", nameof(fileUrl));

            if (!fileExpiresAt.IsSet)
                throw new ArgumentException("Property is required for class Job.", nameof(fileExpiresAt));

            if (!results.IsSet)
                throw new ArgumentException("Property is required for class Job.", nameof(results));

            if (!error.IsSet)
                throw new ArgumentException("Property is required for class Job.", nameof(error));

            if (!finishedAt.IsSet)
                throw new ArgumentException("Property is required for class Job.", nameof(finishedAt));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Job.");

            if (kind.IsSet && kind.Value == null)
                throw new ArgumentNullException(nameof(kind), "Property is not nullable for class Job.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class Job.");

            if (progress.IsSet && progress.Value == null)
                throw new ArgumentNullException(nameof(progress), "Property is not nullable for class Job.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class Job.");

            if (expiresAt.IsSet && expiresAt.Value == null)
                throw new ArgumentNullException(nameof(expiresAt), "Property is not nullable for class Job.");

            return new Job(id.Value!.Value!, kind.Value!, status.Value!, progress.Value!, createdAt.Value!.Value!, expiresAt.Value!.Value!, fileUrl.Value!, fileExpiresAt.Value!, results.Value!, error.Value!, finishedAt.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="Job" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="job"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Job job, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, job, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Job" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="job"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Job job, JsonSerializerOptions jsonSerializerOptions)
        {
            if (job.Kind == null)
                throw new ArgumentNullException(nameof(job.Kind), "Property is required for class Job.");

            if (job.Status == null)
                throw new ArgumentNullException(nameof(job.Status), "Property is required for class Job.");

            if (job.Progress == null)
                throw new ArgumentNullException(nameof(job.Progress), "Property is required for class Job.");

            writer.WriteString("id", job.Id);

            writer.WriteString("kind", job.Kind);

            writer.WriteString("status", job.Status);

            writer.WritePropertyName("progress");
            JsonSerializer.Serialize(writer, job.Progress, jsonSerializerOptions);
            writer.WriteString("created_at", job.CreatedAt.ToString(CreatedAtFormat));

            writer.WriteString("expires_at", job.ExpiresAt.ToString(ExpiresAtFormat));

            if (job.FileUrl != null)
                writer.WriteString("file_url", job.FileUrl);
            else
                writer.WriteNull("file_url");

            if (job.FileExpiresAt != null)
                writer.WriteString("file_expires_at", job.FileExpiresAt.Value.ToString(FileExpiresAtFormat));
            else
                writer.WriteNull("file_expires_at");

            if (job.Results != null)
            {
                writer.WritePropertyName("results");
                JsonSerializer.Serialize(writer, job.Results, jsonSerializerOptions);
            }
            else
                writer.WriteNull("results");
            if (job.Error != null)
                writer.WriteString("error", job.Error);
            else
                writer.WriteNull("error");

            if (job.FinishedAt != null)
                writer.WriteString("finished_at", job.FinishedAt.Value.ToString(FinishedAtFormat));
            else
                writer.WriteNull("finished_at");
        }
    }
}
