// <auto-generated>
/*
 * Dona API
 *
 * Dona API v1 (https://api.dona.im/seller-api/v1) — client generated from the OpenAPI contract. Conventions (auth, errors, idempotency, dry_run, rate limits, 202 held_for_review): https://github.com/ozbuz/dona-api#readme · contract: https://api.dona.im/seller-api/v1/openapi.json
 *
 * The version of the OpenAPI document: v1 (frozen 2026-09-24)
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using Dona.Api.Client;

namespace Dona.Api.Model
{
    /// <summary>
    /// OnKeyExpiringRequest
    /// </summary>
    public partial class OnKeyExpiringRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OnKeyExpiringRequest" /> class.
        /// </summary>
        /// <param name="id">uuidv7 — also the &#x60;/events&#x60; cursor and the webhook &#x60;webhook-id&#x60;.</param>
        /// <param name="type">type</param>
        /// <param name="occurredAt">ISO 8601 with offset (Tashkent &#x60;+05:00&#x60; on output).</param>
        /// <param name="sellerId">sellerId</param>
        /// <param name="apiVersion">apiVersion</param>
        /// <param name="data">data</param>
        /// <param name="links">links</param>
        [JsonConstructor]
        public OnKeyExpiringRequest(Guid id, string type, DateTimeOffset occurredAt, Guid sellerId, ApiVersionEnum apiVersion, KeyEventData data, EventLinks links)
        {
            Id = id;
            Type = type;
            OccurredAt = occurredAt;
            SellerId = sellerId;
            ApiVersion = apiVersion;
            Data = data;
            Links = links;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines ApiVersion
        /// </summary>
        public enum ApiVersionEnum
        {
            /// <summary>
            /// Enum V1 for value: v1
            /// </summary>
            V1 = 1
        }

        /// <summary>
        /// Returns a <see cref="ApiVersionEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ApiVersionEnum ApiVersionEnumFromString(string value)
        {
            if (value.Equals("v1"))
                return ApiVersionEnum.V1;

            throw new NotImplementedException($"Could not convert value to type ApiVersionEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ApiVersionEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ApiVersionEnum? ApiVersionEnumFromStringOrDefault(string value)
        {
            if (value.Equals("v1"))
                return ApiVersionEnum.V1;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ApiVersionEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ApiVersionEnumToJsonValue(ApiVersionEnum value)
        {
            if (value == ApiVersionEnum.V1)
                return "v1";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets ApiVersion
        /// </summary>
        [JsonPropertyName("api_version")]
        public ApiVersionEnum ApiVersion { get; set; }

        /// <summary>
        /// uuidv7 — also the &#x60;/events&#x60; cursor and the webhook &#x60;webhook-id&#x60;.
        /// </summary>
        /// <value>uuidv7 — also the &#x60;/events&#x60; cursor and the webhook &#x60;webhook-id&#x60;.</value>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public string Type { get; set; }

        /// <summary>
        /// ISO 8601 with offset (Tashkent &#x60;+05:00&#x60; on output).
        /// </summary>
        /// <value>ISO 8601 with offset (Tashkent &#x60;+05:00&#x60; on output).</value>
        [JsonPropertyName("occurred_at")]
        public DateTimeOffset OccurredAt { get; set; }

        /// <summary>
        /// Gets or Sets SellerId
        /// </summary>
        [JsonPropertyName("seller_id")]
        public Guid SellerId { get; set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [JsonPropertyName("data")]
        public KeyEventData Data { get; set; }

        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [JsonPropertyName("links")]
        public EventLinks Links { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OnKeyExpiringRequest {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  OccurredAt: ").Append(OccurredAt).Append("\n");
            sb.Append("  SellerId: ").Append(SellerId).Append("\n");
            sb.Append("  ApiVersion: ").Append(ApiVersion).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OnKeyExpiringRequest" />
    /// </summary>
    public partial class OnKeyExpiringRequestJsonConverter : JsonConverter<OnKeyExpiringRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="OnKeyExpiringRequestJsonConverter" /> class.
        /// </summary>
        public OnKeyExpiringRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize OccurredAt
        /// </summary>
        public string OccurredAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="OnKeyExpiringRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OnKeyExpiringRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<string?> type = default;
            Option<DateTimeOffset?> occurredAt = default;
            Option<Guid?> sellerId = default;
            Option<OnKeyExpiringRequest.ApiVersionEnum?> apiVersion = default;
            Option<KeyEventData?> data = default;
            Option<EventLinks?> links = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "type":
                            type = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "occurred_at":
                            occurredAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "seller_id":
                            sellerId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "api_version":
                            string? apiVersionRawValue = utf8JsonReader.GetString();
                            if (apiVersionRawValue != null)
                            {
                                OnKeyExpiringRequest.ApiVersionEnum? apiVersionValue = OnKeyExpiringRequest.ApiVersionEnumFromStringOrDefault(apiVersionRawValue);
                                if (apiVersionValue == null)
                                    throw new JsonException();
                                apiVersion = new Option<OnKeyExpiringRequest.ApiVersionEnum?>(apiVersionValue);
                            }
                            break;
                        case "data":
                            data = new Option<KeyEventData?>(JsonSerializer.Deserialize<KeyEventData>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "links":
                            links = new Option<EventLinks?>(JsonSerializer.Deserialize<EventLinks>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class OnKeyExpiringRequest.", nameof(id));

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class OnKeyExpiringRequest.", nameof(type));

            if (!occurredAt.IsSet)
                throw new ArgumentException("Property is required for class OnKeyExpiringRequest.", nameof(occurredAt));

            if (!sellerId.IsSet)
                throw new ArgumentException("Property is required for class OnKeyExpiringRequest.", nameof(sellerId));

            if (!apiVersion.IsSet)
                throw new ArgumentException("Property is required for class OnKeyExpiringRequest.", nameof(apiVersion));

            if (!data.IsSet)
                throw new ArgumentException("Property is required for class OnKeyExpiringRequest.", nameof(data));

            if (!links.IsSet)
                throw new ArgumentException("Property is required for class OnKeyExpiringRequest.", nameof(links));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class OnKeyExpiringRequest.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class OnKeyExpiringRequest.");

            if (occurredAt.IsSet && occurredAt.Value == null)
                throw new ArgumentNullException(nameof(occurredAt), "Property is not nullable for class OnKeyExpiringRequest.");

            if (sellerId.IsSet && sellerId.Value == null)
                throw new ArgumentNullException(nameof(sellerId), "Property is not nullable for class OnKeyExpiringRequest.");

            if (apiVersion.IsSet && apiVersion.Value == null)
                throw new ArgumentNullException(nameof(apiVersion), "Property is not nullable for class OnKeyExpiringRequest.");

            if (data.IsSet && data.Value == null)
                throw new ArgumentNullException(nameof(data), "Property is not nullable for class OnKeyExpiringRequest.");

            if (links.IsSet && links.Value == null)
                throw new ArgumentNullException(nameof(links), "Property is not nullable for class OnKeyExpiringRequest.");

            return new OnKeyExpiringRequest(id.Value!.Value!, type.Value!, occurredAt.Value!.Value!, sellerId.Value!.Value!, apiVersion.Value!.Value!, data.Value!, links.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="OnKeyExpiringRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="onKeyExpiringRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OnKeyExpiringRequest onKeyExpiringRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, onKeyExpiringRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OnKeyExpiringRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="onKeyExpiringRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OnKeyExpiringRequest onKeyExpiringRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (onKeyExpiringRequest.Type == null)
                throw new ArgumentNullException(nameof(onKeyExpiringRequest.Type), "Property is required for class OnKeyExpiringRequest.");

            if (onKeyExpiringRequest.Data == null)
                throw new ArgumentNullException(nameof(onKeyExpiringRequest.Data), "Property is required for class OnKeyExpiringRequest.");

            if (onKeyExpiringRequest.Links == null)
                throw new ArgumentNullException(nameof(onKeyExpiringRequest.Links), "Property is required for class OnKeyExpiringRequest.");

            writer.WriteString("id", onKeyExpiringRequest.Id);

            writer.WriteString("type", onKeyExpiringRequest.Type);

            writer.WriteString("occurred_at", onKeyExpiringRequest.OccurredAt.ToString(OccurredAtFormat));

            writer.WriteString("seller_id", onKeyExpiringRequest.SellerId);

            var apiVersionRawValue = OnKeyExpiringRequest.ApiVersionEnumToJsonValue(onKeyExpiringRequest.ApiVersion);
            writer.WriteString("api_version", apiVersionRawValue);
            writer.WritePropertyName("data");
            JsonSerializer.Serialize(writer, onKeyExpiringRequest.Data, jsonSerializerOptions);
            writer.WritePropertyName("links");
            JsonSerializer.Serialize(writer, onKeyExpiringRequest.Links, jsonSerializerOptions);
        }
    }
}
