// <auto-generated>
/*
 * Dona API
 *
 * Dona API v1 (https://api.dona.im/seller-api/v1) — client generated from the OpenAPI contract. Conventions (auth, errors, idempotency, dry_run, rate limits, 202 held_for_review): https://github.com/ozbuz/dona-api#readme · contract: https://api.dona.im/seller-api/v1/openapi.json
 *
 * The version of the OpenAPI document: v1 (frozen 2026-09-24)
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using Dona.Api.Client;

namespace Dona.Api.Model
{
    /// <summary>
    /// OrderLineCancelledEventData
    /// </summary>
    public partial class OrderLineCancelledEventData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderLineCancelledEventData" /> class.
        /// </summary>
        /// <param name="orderId">orderId</param>
        /// <param name="orderItemId">orderItemId</param>
        /// <param name="quantity">quantity</param>
        /// <param name="reasonCode">A code from the order vocabularies, or null — the buyer&#39;s free text is never pushed.</param>
        [JsonConstructor]
        public OrderLineCancelledEventData(Guid orderId, Guid orderItemId, int quantity, string? reasonCode = default)
        {
            OrderId = orderId;
            OrderItemId = orderItemId;
            Quantity = quantity;
            ReasonCode = reasonCode;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets OrderId
        /// </summary>
        [JsonPropertyName("order_id")]
        public Guid OrderId { get; set; }

        /// <summary>
        /// Gets or Sets OrderItemId
        /// </summary>
        [JsonPropertyName("order_item_id")]
        public Guid OrderItemId { get; set; }

        /// <summary>
        /// Gets or Sets Quantity
        /// </summary>
        [JsonPropertyName("quantity")]
        public int Quantity { get; set; }

        /// <summary>
        /// A code from the order vocabularies, or null — the buyer&#39;s free text is never pushed.
        /// </summary>
        /// <value>A code from the order vocabularies, or null — the buyer&#39;s free text is never pushed.</value>
        [JsonPropertyName("reason_code")]
        public string? ReasonCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderLineCancelledEventData {\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  OrderItemId: ").Append(OrderItemId).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  ReasonCode: ").Append(ReasonCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OrderLineCancelledEventData" />
    /// </summary>
    public partial class OrderLineCancelledEventDataJsonConverter : JsonConverter<OrderLineCancelledEventData>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="OrderLineCancelledEventDataJsonConverter" /> class.
        /// </summary>
        public OrderLineCancelledEventDataJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="OrderLineCancelledEventData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OrderLineCancelledEventData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> orderId = default;
            Option<Guid?> orderItemId = default;
            Option<int?> quantity = default;
            Option<string?> reasonCode = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "order_id":
                            orderId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "order_item_id":
                            orderItemId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "quantity":
                            quantity = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "reason_code":
                            reasonCode = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!orderId.IsSet)
                throw new ArgumentException("Property is required for class OrderLineCancelledEventData.", nameof(orderId));

            if (!orderItemId.IsSet)
                throw new ArgumentException("Property is required for class OrderLineCancelledEventData.", nameof(orderItemId));

            if (!quantity.IsSet)
                throw new ArgumentException("Property is required for class OrderLineCancelledEventData.", nameof(quantity));

            if (!reasonCode.IsSet)
                throw new ArgumentException("Property is required for class OrderLineCancelledEventData.", nameof(reasonCode));

            if (orderId.IsSet && orderId.Value == null)
                throw new ArgumentNullException(nameof(orderId), "Property is not nullable for class OrderLineCancelledEventData.");

            if (orderItemId.IsSet && orderItemId.Value == null)
                throw new ArgumentNullException(nameof(orderItemId), "Property is not nullable for class OrderLineCancelledEventData.");

            if (quantity.IsSet && quantity.Value == null)
                throw new ArgumentNullException(nameof(quantity), "Property is not nullable for class OrderLineCancelledEventData.");

            return new OrderLineCancelledEventData(orderId.Value!.Value!, orderItemId.Value!.Value!, quantity.Value!.Value!, reasonCode.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="OrderLineCancelledEventData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="orderLineCancelledEventData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OrderLineCancelledEventData orderLineCancelledEventData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, orderLineCancelledEventData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OrderLineCancelledEventData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="orderLineCancelledEventData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OrderLineCancelledEventData orderLineCancelledEventData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteString("order_id", orderLineCancelledEventData.OrderId);

            writer.WriteString("order_item_id", orderLineCancelledEventData.OrderItemId);

            writer.WriteNumber("quantity", orderLineCancelledEventData.Quantity);

            if (orderLineCancelledEventData.ReasonCode != null)
                writer.WriteString("reason_code", orderLineCancelledEventData.ReasonCode);
            else
                writer.WriteNull("reason_code");
        }
    }
}
