// <auto-generated>
/*
 * Dona API
 *
 * Dona API v1 (https://api.dona.im/seller-api/v1) — client generated from the OpenAPI contract. Conventions (auth, errors, idempotency, dry_run, rate limits, 202 held_for_review): https://github.com/ozbuz/dona-api#readme · contract: https://api.dona.im/seller-api/v1/openapi.json
 *
 * The version of the OpenAPI document: v1 (frozen 2026-09-24)
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using Dona.Api.Client;

namespace Dona.Api.Model
{
    /// <summary>
    /// Ping
    /// </summary>
    public partial class Ping
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Ping" /> class.
        /// </summary>
        /// <param name="ok">ok</param>
        /// <param name="time">ISO 8601 with offset (Tashkent &#x60;+05:00&#x60; on output).</param>
        /// <param name="authenticated">True only when a valid key was presented.</param>
        [JsonConstructor]
        public Ping(OkEnum ok, DateTimeOffset time, bool authenticated)
        {
            Ok = ok;
            Time = time;
            Authenticated = authenticated;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Ok
        /// </summary>
        public enum OkEnum
        {
            /// <summary>
            /// Enum Pong for value: pong
            /// </summary>
            Pong = 1
        }

        /// <summary>
        /// Returns a <see cref="OkEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static OkEnum OkEnumFromString(string value)
        {
            if (value.Equals("pong"))
                return OkEnum.Pong;

            throw new NotImplementedException($"Could not convert value to type OkEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="OkEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static OkEnum? OkEnumFromStringOrDefault(string value)
        {
            if (value.Equals("pong"))
                return OkEnum.Pong;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="OkEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string OkEnumToJsonValue(OkEnum value)
        {
            if (value == OkEnum.Pong)
                return "pong";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Ok
        /// </summary>
        [JsonPropertyName("ok")]
        public OkEnum Ok { get; set; }

        /// <summary>
        /// ISO 8601 with offset (Tashkent &#x60;+05:00&#x60; on output).
        /// </summary>
        /// <value>ISO 8601 with offset (Tashkent &#x60;+05:00&#x60; on output).</value>
        [JsonPropertyName("time")]
        public DateTimeOffset Time { get; set; }

        /// <summary>
        /// True only when a valid key was presented.
        /// </summary>
        /// <value>True only when a valid key was presented.</value>
        [JsonPropertyName("authenticated")]
        public bool Authenticated { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Ping {\n");
            sb.Append("  Ok: ").Append(Ok).Append("\n");
            sb.Append("  Time: ").Append(Time).Append("\n");
            sb.Append("  Authenticated: ").Append(Authenticated).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Ping" />
    /// </summary>
    public partial class PingJsonConverter : JsonConverter<Ping>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="PingJsonConverter" /> class.
        /// </summary>
        public PingJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize Time
        /// </summary>
        public string TimeFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="Ping" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Ping Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Ping.OkEnum?> ok = default;
            Option<DateTimeOffset?> time = default;
            Option<bool?> authenticated = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "ok":
                            string? okRawValue = utf8JsonReader.GetString();
                            if (okRawValue != null)
                            {
                                Ping.OkEnum? okValue = Ping.OkEnumFromStringOrDefault(okRawValue);
                                if (okValue == null)
                                    throw new JsonException();
                                ok = new Option<Ping.OkEnum?>(okValue);
                            }
                            break;
                        case "time":
                            time = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "authenticated":
                            authenticated = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!ok.IsSet)
                throw new ArgumentException("Property is required for class Ping.", nameof(ok));

            if (!time.IsSet)
                throw new ArgumentException("Property is required for class Ping.", nameof(time));

            if (!authenticated.IsSet)
                throw new ArgumentException("Property is required for class Ping.", nameof(authenticated));

            if (ok.IsSet && ok.Value == null)
                throw new ArgumentNullException(nameof(ok), "Property is not nullable for class Ping.");

            if (time.IsSet && time.Value == null)
                throw new ArgumentNullException(nameof(time), "Property is not nullable for class Ping.");

            if (authenticated.IsSet && authenticated.Value == null)
                throw new ArgumentNullException(nameof(authenticated), "Property is not nullable for class Ping.");

            return new Ping(ok.Value!.Value!, time.Value!.Value!, authenticated.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="Ping" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ping"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Ping ping, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, ping, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Ping" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ping"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Ping ping, JsonSerializerOptions jsonSerializerOptions)
        {
            var okRawValue = Ping.OkEnumToJsonValue(ping.Ok);
            writer.WriteString("ok", okRawValue);
            writer.WriteString("time", ping.Time.ToString(TimeFormat));

            writer.WriteBoolean("authenticated", ping.Authenticated);
        }
    }
}
