// <auto-generated>
/*
 * Dona API
 *
 * Dona API v1 (https://api.dona.im/seller-api/v1) — client generated from the OpenAPI contract. Conventions (auth, errors, idempotency, dry_run, rate limits, 202 held_for_review): https://github.com/ozbuz/dona-api#readme · contract: https://api.dona.im/seller-api/v1/openapi.json
 *
 * The version of the OpenAPI document: v1 (frozen 2026-09-24)
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using Dona.Api.Client;

namespace Dona.Api.Model
{
    /// <summary>
    /// ReturnEventData
    /// </summary>
    public partial class ReturnEventData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReturnEventData" /> class.
        /// </summary>
        /// <param name="returnId">returnId</param>
        /// <param name="orderId">orderId</param>
        /// <param name="status">status</param>
        /// <param name="dueAt">dueAt</param>
        [JsonConstructor]
        public ReturnEventData(Guid returnId, Guid orderId, string status, Option<DateTimeOffset?> dueAt = default)
        {
            ReturnId = returnId;
            OrderId = orderId;
            Status = status;
            DueAtOption = dueAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets ReturnId
        /// </summary>
        [JsonPropertyName("return_id")]
        public Guid ReturnId { get; set; }

        /// <summary>
        /// Gets or Sets OrderId
        /// </summary>
        [JsonPropertyName("order_id")]
        public Guid OrderId { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string Status { get; set; }

        /// <summary>
        /// Used to track the state of DueAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTimeOffset?> DueAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets DueAt
        /// </summary>
        [JsonPropertyName("due_at")]
        public DateTimeOffset? DueAt { get { return this.DueAtOption.Value; } set { this.DueAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReturnEventData {\n");
            sb.Append("  ReturnId: ").Append(ReturnId).Append("\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  DueAt: ").Append(DueAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ReturnEventData" />
    /// </summary>
    public partial class ReturnEventDataJsonConverter : JsonConverter<ReturnEventData>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ReturnEventDataJsonConverter" /> class.
        /// </summary>
        public ReturnEventDataJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize DueAt
        /// </summary>
        public string DueAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="ReturnEventData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ReturnEventData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> returnId = default;
            Option<Guid?> orderId = default;
            Option<string?> status = default;
            Option<DateTimeOffset?> dueAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "return_id":
                            returnId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "order_id":
                            orderId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "due_at":
                            dueAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!returnId.IsSet)
                throw new ArgumentException("Property is required for class ReturnEventData.", nameof(returnId));

            if (!orderId.IsSet)
                throw new ArgumentException("Property is required for class ReturnEventData.", nameof(orderId));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class ReturnEventData.", nameof(status));

            if (returnId.IsSet && returnId.Value == null)
                throw new ArgumentNullException(nameof(returnId), "Property is not nullable for class ReturnEventData.");

            if (orderId.IsSet && orderId.Value == null)
                throw new ArgumentNullException(nameof(orderId), "Property is not nullable for class ReturnEventData.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class ReturnEventData.");

            return new ReturnEventData(returnId.Value!.Value!, orderId.Value!.Value!, status.Value!, dueAt);
        }

        /// <summary>
        /// Serializes a <see cref="ReturnEventData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="returnEventData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ReturnEventData returnEventData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, returnEventData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ReturnEventData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="returnEventData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ReturnEventData returnEventData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (returnEventData.Status == null)
                throw new ArgumentNullException(nameof(returnEventData.Status), "Property is required for class ReturnEventData.");

            writer.WriteString("return_id", returnEventData.ReturnId);

            writer.WriteString("order_id", returnEventData.OrderId);

            writer.WriteString("status", returnEventData.Status);

            if (returnEventData.DueAtOption.IsSet)
                if (returnEventData.DueAtOption.Value != null)
                    writer.WriteString("due_at", returnEventData.DueAtOption.Value!.Value.ToString(DueAtFormat));
                else
                    writer.WriteNull("due_at");
        }
    }
}
